<a href="https://colab.research.google.com/github/burloi-ship-it/ml-product-classification/blob/main/model/ml_product_classification_export.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# We will
- import pandas libraries
- load the dataset into a dataframe
- preview first 5 rows
- count number of rows in dataframe
- print number of missing values in each column in dataframe
- preview dataframe columns data types

In [16]:
import pandas as pd

# load dataset from GitHub
url = "https://raw.githubusercontent.com/burloi-ship-it/ml-product-classification/refs/heads/main/data/products.csv"

# load data into a dataframe
df = pd.read_csv(url)

# first 5 rows
print(f"\nFirst 5 rows: \n")
display(df.head(5))

# number of rows in dataframe
print(f"\nRows in dataframe: \n")
print(df.shape[0])

# number of missing values
print(f"\nNumber of missing values: \n")
print(df.isna().sum())

# column data types and non null counts
print("\nColumn data types: ")
print(df.info())

First 5 rows:

,product ID,Product Title,Merchant ID,Category Label,_Product Code,Number_of_Views,Merchant Rating,Listing Date
0,1,apple iphone 8 plus 64gb silver,1,Mobile Phones,QA-2276-XC,860.0,2.5,5/10/2024
1,2,apple iphone 8 plus 64 gb spacegrau,2,Mobile Phones,KA-2501-QO,3772.0,4.8,12/31/2024
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,Mobile Phones,FP-8086-IE,3092.0,3.9,11/10/2024
3,4,apple iphone 8 plus 64gb space grey,4,Mobile Phones,YI-0086-US,466.0,3.4,5/2/2022
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,Mobile Phones,NZ-3586-WP,4426.0,1.6,4/12/2023

Rows in dataframe:

35311

Number of missing values:

product ID           0
Product Title      172
Merchant ID          0
 Category Label     44
_Product Code       95
Number_of_Views     14
Merchant Rating    170
 Listing Date       59
dtype: int64

Column data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35311 entries, 0 to 35310
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product ID       35311 non-null  int64
 1   Product Title    35139 non-null  object
 2   Merchant ID      35311 non-null  int64
 3    Category Label  35267 non-null  object
 4   _Product Code    35216 non-null  object
 5   Number_of_Views  35297 non-null  float64
 6   Merchant Rating  35141 non-null  float64
 7    Listing Date    35252 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 2.2+ MB
None

## We will:

- rename columns for better preview and data manipulation
- remove dataframe NaN values
- check dataframe NaN values number
- standardize to lowercase text in 'product_title' and 'category_label' columns
- convert to datetime format 'listing_date' column
- convert to category format 'category_label'
- convert to Int64 format 'number_of_views'
- list actual available column names
- display dataframe current columns data types

In [17]:
# rename columns for clear view and better processing
print(f"Renaming columns in dataset...")
df = df.rename(columns={'product ID': 'product_id', 'Product Title': 'product_title', 'Merchant ID': 'merchant_id', ' Category Label': 'category_label', '_Product Code': 'product_code', 'Number_of_Views': 'number_of_views', 'Merchant Rating': 'merchant_rating', ' Listing Date  ': 'listing_date'})
print(f"Done!")

# stergerea valorilor NaN
print(f"\nDropping missing values in dataset...")
df = df.dropna()
print(f"Done!")
# verificarea numarului de valori nule din coloane
print("\nCurrent number of missing values: ")
print(df.isna().sum())

# standardizarea textului coloanelor 'product_title' si 'category_label'
print(f"\nStandardizing 'product_title' and 'category_label' columns to lowercase text...")
df['product_title'] = df['product_title'].str.lower()
df['category_label'] = df['category_label'].str.lower()
print(f"Done!")

# conversia coloanei 'listing_date' in format datetime
print(f"\nConverting 'listing_date' column in datetime format...")
df['listing_date'] = pd.to_datetime(df['listing_date'], format="%m/%d/%Y", errors="coerce")
print(f"Done!")

# conversia coloanei 'category_label' in tip category
print(f"\nConverting 'category_label' column in object type...")
df['category_label'] = df['category_label'].astype('category')
print(f"Done!")

# conversia coloanei 'number_of_views' in tip Int64
print(f"\nConverting 'number_of_views' column in Int64 type...")
df['number_of_views'] = df['number_of_views'].astype('Int64')
print(f"Done!")

# listarea coloanelor actuale
print("\nListing current columns in dataset: ")
print(*df.columns, sep='\n')

# listarea tipului de date ale coloanelor dupa conversie
print(f"\nNew available columns data types: \n")
print(df.info())

Renaming columns in dataset...
Done!

Dropping missing values in dataset...
Done!

Current number of missing values:
product_id         0
product_title      0
merchant_id        0
category_label     0
product_code       0
number_of_views    0
merchant_rating    0
listing_date       0
dtype: int64

Standardizing 'product_title' and 'category_label' columns to lowercase text...
Done!

Converting 'listing_date' column in datetime format...
Done!

Converting 'category_label' column in object type...
Done!

Converting 'number_of_views' column in Int64 type...
Done!

Listing current columns in dataset:
product_id
product_title
merchant_id
category_label
product_code
number_of_views
merchant_rating
listing_date

New available columns data types:

<class 'pandas.core.frame.DataFrame'>
Index: 34760 entries, 0 to 35310
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_id       34760 non-null  int64
 1   product_title    34760 non-null  object
 2   merchant_id      34760 non-null  int64
 3   category_label   34760 non-null  category
 4   product_code     34760 non-null  object
 5   number_of_views  34760 non-null  Int64
 6   merchant_rating  34760 non-null  float64
 7   listing_date     34760 non-null  datetime64[ns]
dtypes: Int64(1), category(1), datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 2.2+ MB
None

## We will:

- drop irrelevant columns in dataframe - product_id, product_code, number_of_views, merchant_rating, listing_date
- list actual available dataframe columns

In [18]:
# dropping irrelevant columns
print(f"\nDropping irrelevant columns for model training and prediction...")
df = df.drop(columns=['product_id','product_code', 'number_of_views', 'merchant_rating', 'listing_date'])
print(f"Done!")

# listing actual dataframe columns
print(f"\nCurrent dataframe available columns: ")
print(*df.columns, sep='\n')

Dropping irrelevant columns for model training and prediction...
Done!

Current dataframe available columns:
product_title
merchant_id
category_label

## We will:

- import re module
- create 'extract_storage' function, 'extract_brand' and 'extract_color' function to apply on 'product_title' column
- create new columns 'storage_gb' , 'brand' and 'color' for better prediction training
- compact 'category_label' column and keep only one category for mobile phones and fridges from all names belonging to these categories available
- display the dataframe with current columns

In [19]:
# function to extract brand and storage
import re
def extract_storage(title):
  match = re.search(r'(\d+)\s*gb', title.lower())
  return int(match.group(1)) if match else None

# extract brand
def extract_brand(title, brand_list):
  title_lower = title.lower()
  for brand in brand_list:
    if brand in title_lower:
      return brand
  return 'Unknown'

# color extraction
def extract_color(title, color_list):
  title_lower = title.lower()
  for color in color_list:
    if color in title_lower:
      return color
  return 'Unknown'

# storage single argument function , apply directly
df['storage_gb'] = df['product_title'].apply(extract_storage)

# brand - use lambda for brand_list argument
brand_list = ['apple', 'samsung', 'huawei', 'xiaomi', 'nokia', 'sony', 'google', 'oneplus']
df['brand'] = df['product_title'].apply(lambda x: extract_brand(x, brand_list))

# color extraction
color_list = ['silver', 'black', 'white', 'gold', 'spacegrau', 'space grey', 'blue', 'red']
df['color'] = df['product_title'].apply(lambda x: extract_color(x, color_list))

label_map = {'cpu':'cpus', 'fridge':'fridges', 'mobile phone':'mobile phones'}
df['category_label'] = df['category_label'].str.strip().str.lower().replace(label_map)


display(df)

,product_title,merchant_id,category_label,storage_gb,brand,color
0,apple iphone 8 plus 64gb silver,1,mobile phones,64.0,apple,silver
1,apple iphone 8 plus 64 gb spacegrau,2,mobile phones,64.0,apple,spacegrau
2,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,mobile phones,64.0,apple,gold
3,apple iphone 8 plus 64gb space grey,4,mobile phones,64.0,apple,space grey
4,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,mobile phones,64.0,apple,gold
...,...,...,...,...,...,...
35306,smeg fab28 60cm retro style right hand hinge f...,59,fridges,NaN,Unknown,Unknown
35307,smeg fab28 60cm retro style left hand hinge fr...,59,fridges,NaN,Unknown,red
35308,smeg fab28 60cm retro style left hand hinge fr...,59,fridges,NaN,Unknown,Unknown
35309,candy 60cm built under larder fridge cru160nek,125,fridges,NaN,Unknown,Unknown
35310,neff k4316x7gb built under larder fridge,179,fridges,7.0,Unknown,Unknown

## We will

- import 'train_test_split' for dataset splitting into train sample and test sample
- split data in training sample 80%, keep 20% from dataset for testing prediction

In [20]:
# split data for train and test
from sklearn.model_selection import train_test_split

# Training models on data
# Features and labels
x = df[['product_title', 'merchant_id', 'storage_gb', 'brand', 'color']]
y = df['category_label']

# Splitting data in train data 80% and test data 20%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

## We will:

- import modules to handle term frequency vectorization
- import modules to handle categorical 'brand' ,'color' and 'merchant'
- build the preprocessor

In [21]:
# vectorization
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

numeric_pipeline = Pipeline([('impute', SimpleImputer(strategy='median'))])

preprocessor = ColumnTransformer([
    ('title', TfidfVectorizer(analyzer='char_wb', ngram_range=(2, 4)), 'product_title'), # spacegrau vs space grey
    ('merchant', OneHotEncoder(handle_unknown='ignore'), ['merchant_id']),
    ('storage', numeric_pipeline, ['storage_gb']),
    ('brand', OneHotEncoder(handle_unknown='ignore'), ['brand']),
    ('color', OneHotEncoder(handle_unknown='ignore'), ['color'])
])

## We will:

- import RandomForestClassifier model
- create a dictionary containing models for testing
- create a iteration through models list and apply a pipeline containing model to training datasets
- use the pipeline on testing dataset for prediction
- print model stats - accuracy, f1-score, precision, recall

In [22]:
# model testing
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# list of classifiers
models = {
    "Random Forest": RandomForestClassifier()
}

# train and test models
for name, model in models.items():
  print(f"\n{name}")
  pipeline = Pipeline([
      ("preprocessing", preprocessor),
      ("classifier", model)
  ])

  pipeline.fit(x_train, y_train)

Random Forest

In [23]:
# import joblib module and save the model to a file
import os
import joblib
os.makedirs('model', exist_ok=True)

joblib.dump(pipeline, 'model/trained_model.pkl')

print('Model saved as model/trained_model.pkl')

Model saved as model/trained_model.pkl